import { groupBy } from './utils';

export const algorithms = [
    {
        id: 'BubbleSort',
        name: 'Bubble Sort',
        category: 'Sorting',
        meta: 'Discover how elements are repeatedly compared and swapped to achieve a sorted order in Bubble Sort.',
        meta_bn: 'বাবল সর্টে কিভাবে উপাদানগুলো বারবার তুলনা এবং বিনিময় করা হয় যাতে একটি সাজানো ক্রম তৈরি হয় তা শিখুন।',
    },
    {
        id: 'InsertionSort',
        name: 'Insertion Sort',
        category: 'Sorting',
        meta: 'Discover how Insertion Sort works by sorting one element at a time, like placing a new card in the right spot of a sorted hand.',
        meta_bn: 'ইনসারশন সর্ট একবারে একটি উপাদান সাজানোর মাধ্যমে কাজ করে, যেমন সাজানো কার্ডের মধ্যে নতুন কার্ড সঠিক স্থানে রাখা।',
    },
    {
        id: 'SelectionSort',
        name: 'Selection Sort',
        category: 'Sorting',
        meta: 'Explore how Selection Sort finds the smallest item and places it at the correct position in each iteration.',
        meta_bn: 'সিলেকশন সর্ট কিভাবে সবচেয়ে ছোট উপাদান খুঁজে বের করে এবং প্রতিটি পুনরাবৃত্তিতে সঠিক স্থানে রাখে তা জানুন।',
    },
    {
        id: 'RadixSort',
        name: 'Radix Sort',
        category: 'Sorting',
        meta: 'Discover how numbers are sorted digit by digit (by placing them into buckets) in this unique algorithm called Radix Sort.',
        meta_bn: 'রেডিক্স সর্টে সংখ্যা কীভাবে ডিজিট অনুযায়ী (বাকেটে রেখে) সাজানো হয় তা শিখুন।',
    },
    {
        id: 'HeapSort',
        name: 'Heap Sort',
        category: 'Sorting',
        meta: 'Learn Heap Sort with interactive visuals that show how elements are organized and sorted in a heap structure for a clear understanding.',
        meta_bn: 'ইন্টারেক্টিভ ভিজ্যুয়াল সহ হিপ সর্ট শিখুন, যা দেখায় উপাদানগুলো কীভাবে হিপ কাঠামোতে সাজানো হয়।',
    },
    {
        id: 'MergeSort',
        name: 'Merge Sort',
        category: 'Sorting',
        meta: 'See how the Merge Sort algorithm divides and combines data step-by-step with visual aids that make learning this method simple and engaging.',
        meta_bn: 'মার্জ সর্ট কিভাবে ধাপে ধাপে ডেটা ভাগ ও একত্রিত করে তা ভিজ্যুয়াল সাহায্য নিয়ে শিখুন।',
    },
    {
        id: 'QuickSort',
        name: 'Quick Sort',
        category: 'Sorting',
        meta: 'See how data is partitioned and sorted efficiently in each step of this fast sorting algorithm called Quick Sort.',
        meta_bn: 'কুইক সর্টে কিভাবে ডেটা পার্টিশন করা হয় এবং প্রতিটি ধাপে দ্রুতভাবে সাজানো হয় তা শিখুন।',
    },
    {
        id: 'DFS',
        name: 'Depth First Search',
        category: 'Graph',
        meta: 'Explore Depth-First Search (DFS) and learn how this graph traversal algorithm works by visiting nodes deeply before backtracking.',
        meta_bn: 'ডেপথ-ফার্স্ট সার্চ (DFS) শিখুন এবং জানুন কিভাবে এটি নোডগুলো গভীরভাবে ঘুরে আগে ফিরে আসে।',
    },
    {
        id: 'BFS',
        name: 'Breadth First Search',
        category: 'Graph',
        meta: 'Explore Breadth-First Search (BFS) and learn how this graph traversal algorithm explores all nodes level by level in a graph.',
        meta_bn: 'ব্রেডথ-ফার্স্ট সার্চ (BFS) শিখুন এবং দেখুন এটি কিভাবে স্তর অনুযায়ী সমস্ত নোড ঘুরে।',
    },
    {
        id: 'PrimsMST',
        name: "Prim's Algorithm",
        category: 'Graph',
        meta: "Discover how Prim's Algorithm builds a minimum spanning tree by adding the nearest node with minimum weight.",
        meta_bn: 'প্রিমের অ্যালগরিদম কিভাবে ন্যূনতম ওজনযুক্ত নোড যোগ করে একটি মিনিমাম স্প্যানিং ট্রি তৈরি করে তা শিখুন।',
    },
    {
        id: 'KruskalsMST',
        name: "Kruskal's Algorithm",
        category: 'Graph',
        meta: "Explore how Kruskal's Algorithm finds the minimum spanning tree in a graph by connecting edges in order of increasing weight.",
        meta_bn: 'ক্রাস্কালের অ্যালগরিদম কিভাবে ওজন অনুযায়ী এজগুলো যুক্ত করে মিনিমাম স্প্যানিং ট্রি খুঁজে বের করে তা জানুন।',
    },
    {
        id: 'Dijkstra',
        name: "Dijkstra's Algorithm",
        category: 'Graph',
        meta: "Discover how Dijkstra's Algorithm finds the shortest path between nodes in a graph using priority queue.",
        meta_bn: 'ডিজকসট্রার অ্যালগরিদম কিভাবে প্রায়োরিটি কিউ ব্যবহার করে নোডগুলোর মধ্যে সংক্ষিপ্ত পথ খুঁজে বের করে তা শিখুন।',
    },
    {
        id: 'TopSort',
        name: 'Topological Sorting',
        category: 'Graph',
        meta: 'Learn Topological Sorting to order nodes in a directed graph, ensuring that each node appears before its dependencies.',
        meta_bn: 'টপোলজিক্যাল সর্টিং শিখুন যাতে প্রতিটি নোড তার নির্ভরশীলতার আগে আসে।',
    },
    {
        id: 'Hamiltonian',
        name: 'Hamiltonian Cycle',
        category: 'Graph',
        meta: 'Learn about Hamiltonian Cycle, a path in a graph that visits each vertex exactly once and returns to the starting point.',
        meta_bn: 'হ্যামিলটনিয়ান সাইকেল সম্পর্কে জানুন, যা প্রতিটি ভার্টেক্স একবারে ঘুরে শুরুতে ফিরে আসে।',
    },
    {
        id: 'BST',
        name: 'Binary Search Tree',
        category: 'Data Structures',
        meta: 'Learn how data is organized in a sorted manner by a Binary Search Tree (BST), allowing for efficient searching, insertion, and deletion.',
        meta_bn: 'বাইনারি সার্চ ট্রি (BST) কিভাবে ডেটা সাজানো রাখে এবং দ্রুত সার্চ, ইনসারশন ও ডিলিশন সম্ভব করে তা শিখুন।',
    },
    {
        id: 'BinaryHeap',
        name: 'Binary Heap',
        category: 'Data Structures',
        meta: 'Explore the Binary Heap where elements are arranged in a binary tree while maintaining priority.',
        meta_bn: 'বাইনারি হিপ শিখুন, যেখানে উপাদানগুলো বাইনারি ট্রি আকারে অগ্রাধিকার অনুযায়ী সাজানো থাকে।',
    },
    {
        id: 'CircularQueue',
        name: 'Circular Queue',
        category: 'Data Structures',
        meta: 'Understand how Circular Queue efficiently manages a fixed-size queue by wrapping around when full.',
        meta_bn: 'সার্কুলার কিউ কিভাবে সীমিত আকারের কিউটি পূর্ণ হলে ঘুরিয়ে পরিচালনা করে তা বোঝুন।',
    },
    {
        id: 'ConvexHull',
        name: 'Convex Hull',
        category: 'Other',
        meta: 'Explore the Convex Hull algorithm to find the smallest convex boundary that encloses a set of points in a plane.',
        meta_bn: 'কনভেক্স হাল অ্যালগরিদম শিখুন যা সমতলে পয়েন্টগুলোর সর্বনিম্ন কনভেক্স সীমা খুঁজে বের করে।',
    },
    {
        id: 'HuffmanCoding',
        name: 'Huffman Coding',
        category: 'Other',
        meta: 'Learn about Huffman Coding, a lossless compression technique that reduces file size by assigning shorter codes to frequent symbols.',
        meta_bn: 'হাফম্যান কোডিং শিখুন, একটি লসলেস কম্প্রেশন প্রযুক্তি যা ঘন ঘন প্রতীকগুলোকে ছোট কোড দেয়।',
    },
   
];

export const categories = groupBy(algorithms, 'category');
